name: Tests

env:
  PYTEST_VERSION: 9.0.2
  RUFF_VERSION: 0.14.14
  RUFF_PY_VERSION: 3.12

on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Test with Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install pytest
        shell: bash
        run: |
          pip install pytest==${{ env.PYTEST_VERSION }}

      - name: Run pytest
        shell: bash
        run: |
          python -m pytest -vvv tests/

  format:
    name: Ruff Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ env.RUFF_PY_VERSION }}

      - name: Install ruff
        shell: bash
        run: |
          pip install ruff==${{ env.RUFF_VERSION }}

      - name: Run ruff format check
        shell: bash
        run: |
          ruff format --check .
